version: 2
notify:
  webhooks:
    # A list of hashes representing hooks. Only the url field is supported.
    - url: https://google.co.in
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: svikramjeet/php7.3:1.0
    steps:
      - checkout
      - run: 
          name: Install Composer
          command: |
            composer self-update
            composer install --prefer-source --no-interaction --dev
      - run:
         name: Unit Tests
         command: |
           ./vendor/phpunit/phpunit/phpunit

workflows:
  version: 2
  validate-and-deploy:
    jobs:
      - build
